[package]
name = "bluefin"
version = "0.1.0"
edition = "2021"
description = "An experimental, secure, P2P, transport-layer protocol."
license = "MIT"
repository = "https://github.com/franklee26/bluefin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
etherparse = "0.13.0"
rand = "0.8.5"
serde = { version = "1.0.147", features = ["derive"]}
thiserror = "1.0.39"
tokio = { version = "1", features = ["full"] }
tun-tap = "0.1.3"
tun = "0.5"

[lib]
name = "bluefin"

[workspace]

members = [
    "demo/client",
    "demo/server",
]
