[package]
name = "bluefin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
etherparse = "0.12.0"
serde = { version = "1.0.147", features = ["derive"]}
tun-tap = "0.1.3"

[lib]
name = "bluefin"

[workspace]

members = [
    "client",
]
